// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	log "go.fork.vn/log"
	handler "go.fork.vn/log/handler"

	mock "github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// AddHandler provides a mock function with given fields: handlerType, _a1
func (_m *MockLogger) AddHandler(handlerType log.HandlerType, _a1 handler.Handler) {
	_m.Called(handlerType, _a1)
}

// MockLogger_AddHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHandler'
type MockLogger_AddHandler_Call struct {
	*mock.Call
}

// AddHandler is a helper method to define mock.On call
//   - handlerType log.HandlerType
//   - _a1 handler.Handler
func (_e *MockLogger_Expecter) AddHandler(handlerType interface{}, _a1 interface{}) *MockLogger_AddHandler_Call {
	return &MockLogger_AddHandler_Call{Call: _e.mock.On("AddHandler", handlerType, _a1)}
}

func (_c *MockLogger_AddHandler_Call) Run(run func(handlerType log.HandlerType, _a1 handler.Handler)) *MockLogger_AddHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.HandlerType), args[1].(handler.Handler))
	})
	return _c
}

func (_c *MockLogger_AddHandler_Call) Return() *MockLogger_AddHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_AddHandler_Call) RunAndReturn(run func(log.HandlerType, handler.Handler)) *MockLogger_AddHandler_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockLogger) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLogger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Close() *MockLogger_Close_Call {
	return &MockLogger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLogger_Close_Call) Run(run func()) *MockLogger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Close_Call) Return(_a0 error) *MockLogger_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_Close_Call) RunAndReturn(run func() error) *MockLogger_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function with given fields: message, args
func (_m *MockLogger) Debug(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debug(message interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(message string, args ...interface{})) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, args
func (_m *MockLogger) Error(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Error(message interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(message string, args ...interface{})) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: message, args
func (_m *MockLogger) Fatal(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Fatal(message interface{}, args ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(message string, args ...interface{})) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// GetHandler provides a mock function with given fields: handlerType
func (_m *MockLogger) GetHandler(handlerType log.HandlerType) handler.Handler {
	ret := _m.Called(handlerType)

	if len(ret) == 0 {
		panic("no return value specified for GetHandler")
	}

	var r0 handler.Handler
	if rf, ok := ret.Get(0).(func(log.HandlerType) handler.Handler); ok {
		r0 = rf(handlerType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.Handler)
		}
	}

	return r0
}

// MockLogger_GetHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHandler'
type MockLogger_GetHandler_Call struct {
	*mock.Call
}

// GetHandler is a helper method to define mock.On call
//   - handlerType log.HandlerType
func (_e *MockLogger_Expecter) GetHandler(handlerType interface{}) *MockLogger_GetHandler_Call {
	return &MockLogger_GetHandler_Call{Call: _e.mock.On("GetHandler", handlerType)}
}

func (_c *MockLogger_GetHandler_Call) Run(run func(handlerType log.HandlerType)) *MockLogger_GetHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.HandlerType))
	})
	return _c
}

func (_c *MockLogger_GetHandler_Call) Return(_a0 handler.Handler) *MockLogger_GetHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_GetHandler_Call) RunAndReturn(run func(log.HandlerType) handler.Handler) *MockLogger_GetHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: message, args
func (_m *MockLogger) Info(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Info(message interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(message string, args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// RemoveHandler provides a mock function with given fields: handlerType
func (_m *MockLogger) RemoveHandler(handlerType log.HandlerType) {
	_m.Called(handlerType)
}

// MockLogger_RemoveHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHandler'
type MockLogger_RemoveHandler_Call struct {
	*mock.Call
}

// RemoveHandler is a helper method to define mock.On call
//   - handlerType log.HandlerType
func (_e *MockLogger_Expecter) RemoveHandler(handlerType interface{}) *MockLogger_RemoveHandler_Call {
	return &MockLogger_RemoveHandler_Call{Call: _e.mock.On("RemoveHandler", handlerType)}
}

func (_c *MockLogger_RemoveHandler_Call) Run(run func(handlerType log.HandlerType)) *MockLogger_RemoveHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.HandlerType))
	})
	return _c
}

func (_c *MockLogger_RemoveHandler_Call) Return() *MockLogger_RemoveHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_RemoveHandler_Call) RunAndReturn(run func(log.HandlerType)) *MockLogger_RemoveHandler_Call {
	_c.Run(run)
	return _c
}

// SetMinLevel provides a mock function with given fields: level
func (_m *MockLogger) SetMinLevel(level handler.Level) {
	_m.Called(level)
}

// MockLogger_SetMinLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMinLevel'
type MockLogger_SetMinLevel_Call struct {
	*mock.Call
}

// SetMinLevel is a helper method to define mock.On call
//   - level handler.Level
func (_e *MockLogger_Expecter) SetMinLevel(level interface{}) *MockLogger_SetMinLevel_Call {
	return &MockLogger_SetMinLevel_Call{Call: _e.mock.On("SetMinLevel", level)}
}

func (_c *MockLogger_SetMinLevel_Call) Run(run func(level handler.Level)) *MockLogger_SetMinLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(handler.Level))
	})
	return _c
}

func (_c *MockLogger_SetMinLevel_Call) Return() *MockLogger_SetMinLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetMinLevel_Call) RunAndReturn(run func(handler.Level)) *MockLogger_SetMinLevel_Call {
	_c.Run(run)
	return _c
}

// Warning provides a mock function with given fields: message, args
func (_m *MockLogger) Warning(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warning'
type MockLogger_Warning_Call struct {
	*mock.Call
}

// Warning is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warning(message interface{}, args ...interface{}) *MockLogger_Warning_Call {
	return &MockLogger_Warning_Call{Call: _e.mock.On("Warning",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Warning_Call) Run(run func(message string, args ...interface{})) *MockLogger_Warning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warning_Call) Return() *MockLogger_Warning_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warning_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Warning_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
