# Log Configuration Sample
# Available handlers: console, file, stack
# Available levels: debug, info, warning, error, fatal

log:
  level: "info"  # debug, info, warning, error, fatal
  console:
    # Enable console logging
    enabled: true  # Enable console logging
    colored: true  # Enable ANSI color codes
  file: 
    # Enable file logging
    enabled: true  # Enable file logging
    path: "storage/logs/app.log"
    max_size: 10485760  # 10MB in bytes (0 for unlimited)
  stack:
    # Enable stack logging
    enabled: true  # Enable stack logging
    handlers:
      console: true
      file: true
